# Generated by Django 5.1 on 2024-08-29 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_project_temp_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='temp_field',
        ),
        migrations.RemoveField(
            model_name='project',
            name='users',
        ),
    ]
